SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
TILESIZE = 64

BACKGROUND_LAYER = 1
TERRAIN_LAYER = 2
PLAYER_LAYER = 3

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
PURPLE = (108, 51, 185)

#-------MAPS---------

#-----SAFEHOUSE-----
SAFEHOUSE = [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTTTTTTTTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTTTTTTTTEBBBBBBBBBBBEBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBPBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBEBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
]
#-------------------

#--------------------