SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
TILESIZE = 64

BACKGROUND_LAYER = 1
TERRAIN_LAYER = 2
PLAYER_LAYER = 3

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

#-------MAPS---------

#-----SAFEHOUSE-----
SAFEHOUSE = [
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTTTTTTTTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTBBBBBBTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBTTTTTTTTBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBPBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBT',
    'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
]
#-------------------

#--------------------